version: "3.8"

services:
  php_fpm_service:
    container_name: php_fpm_service
    build:
      context: ../build/php_fpm
      dockerfile: Dockerfile
    volumes:
      - ../project:/var/www/your_(domain)_dir:ro
    ports:
      - "9003:9003"
    depends_on:
      - nginx_proxy_manager