version: "3.8"

services:
  pma:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    # ports:
    #   - "8888:443"
    env_file:
      - ../env/pma.env
    depends_on:
      - mdb
      - php_fpm_service
      - nginx_proxy_manager